### PR TITLE
Ensure Last Updated dates for Index Only fields are correct

### LINKED ISSUE #37: Incorrect Last Updated dates for Index Only fields
Index Only fields in the data dictionary show the incorrect last updated dates.

For example:
The fields `NETWORK_NAME_TOKEN`, `SUMMARY_TOKEN`, `NAME_TOKEN`, `EMBEDDED_CAST_CHARACTER_NAME_TOKEN`, and `EMBEDDED_CAST_PERSON_NAME_TOKEN` say they were last updated in 1952, but that is incorrect.

### PR DESCRIPTION
**Pull request by foster33**
Last Updated dates for index only fields are now correct.

closes #37

### CODE REVIEW

**Review by cogross — DISMISSED** [review]

**Comment by hlgp** [comment]
noice.  how about a unit test?

File: service/src/main/java/datawave/microservice/metadata/DefaultMetadataFieldScanner.java [hunk 1]
```diff
@@ -277,8 +276,16 @@ private void setType() {
...
+            if (currField.getLastUpdated() != null) {
+                if (Long.parseLong(currField.getLastUpdated()) < Long.parseLong(Instant.ofEpochMilli(currKey.getTimestamp()).atZone(ZoneId.systemDefault())
+                                .toLocalDateTime().format(DateTimeFormatter.ofPattern(TIMESTAMP_FORMAT)))) {
+                    currField.setLastUpdated(Instant.ofEpochMilli(currKey.getTimestamp()).atZone(ZoneId.systemDefault()).toLocalDateTime()
+                                    .format(DateTimeFormatter.ofPattern(TIMESTAMP_FORMAT)));
+                }
+            } else {
+                currField.setLastUpdated(Instant.ofEpochMilli(currKey.getTimestamp()).atZone(ZoneId.systemDefault()).toLocalDateTime()
+                                .format(DateTimeFormatter.ofPattern(TIMESTAMP_FORMAT)));
+            }
```
Comment (apmoriarty) [inline service/src/main/java/datawave/microservice/metadata/DefaultMetadataFieldScanner.java]: Extract the common code to a variable:
```java
 Instant.ofEpochMilli(currKey.getTimestamp())
    .atZone(ZoneId.systemDefault())
    .toLocalDateTime()
    .format(DateTimeFormatter.ofPattern(TIMESTAMP_FORMAT))
```

**Comment by foster33** [comment]
> noice. how about a unit test?

Added a unit test in the latest commit

**Review by ivakegg — APPROVED** [review]
